# Generated by Django 5.2.12 on 2026-03-21 10:12

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('inn', models.CharField(max_length=12)),
                ('kpp', models.CharField(max_length=9)),
                ('legal_address', models.CharField(max_length=500)),
                ('status', models.CharField(choices=[('PENDING', 'На модерации'), ('ACTIVE', 'Активна'), ('BLOCKED', 'Заблокирована')], default='PENDING', max_length=20)),
            ],
            options={
                'ordering': ('name',),
                'unique_together': {('inn', 'kpp')},
            },
        ),
        migrations.CreateModel(
            name='EducatorOrgProfile',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('waste_license_number', models.CharField(max_length=128)),
                ('default_pickup_address', models.CharField(max_length=500)),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='educator_profile', to='organizations.organization')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProcessorOrgProfile',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('recycling_license_number', models.CharField(max_length=128)),
                ('facility_address', models.CharField(max_length=500)),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='processor_profile', to='organizations.organization')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
